server:
  port: 80
  variables:
    dev:
      callbackUrl: "https://2273-59-145-217-117.ngrok-free.app"
      stagingGatewayurl: "https://staging.gateway.proteantech.in/"
      signingPrivateKey: "Un205TSOdDXTq8E+N/sJOLJ8xalnzZ1EUP1Wcv23sKx70fOfFd4Q2bzfpzPQ+6XZhZv65SH7Pr6YMk8SuFHpxQ=="
      bapId: "mobility-staging.ondc.org"
      uniqueKeyId: "UK-MOBILITY"
    prod:
      callbackUrl: "https://2273-59-145-217-117.ngrok-free.app"
      stagingGatewayurl: "https://staging.gateway.proteantech.in/"
      signingPrivateKey: "Un205TSOdDXTq8E+N/sJOLJ8xalnzZ1EUP1Wcv23sKx70fOfFd4Q2bzfpzPQ+6XZhZv65SH7Pr6YMk8SuFHpxQ=="
      bapId: "mobility-staging.ondc.org"
      uniqueKeyId: "UK-MOBILITY"
flows:
  # - summary: metro complete flow
  #   id: metro-flow-1
  #   domain: ONDC:TRV11
  #   input:
  #     $ref: File:///configs/metro-flow-1/input.yaml
  #   protocol:
  #     $ref: File:///configs/metro-flow-1/protocolMapping.yaml
  #   calls:
  #     $ref: File:///configs/metro-flow-1/protocolCalls.yaml
  # - summary: metro flow without select call
  #   id: metro-flow-2
  #   domain: ONDC:TRV11
  #   sessionData:
  #     collectedBy: BAP
  #     bankAccountNumber: "123456789"
  #     virtualPaymentAddress: "adasd@okiciic"
  #     bankCode: "fj3jf9ij3f02"
  #   input:
  #     $ref: File:///configs/metro-flow-2/input.yaml
  #   protocol:
  #     $ref: File:///configs/metro-flow-2/protocolMapping.yaml
  #   calls:
  #     $ref: File:///configs/metro-flow-2/protocolCalls.yaml
  - summary: on demand complete flow
    domain: ONDC:TRV10
    id: ondemand-flow-1
    input:
      $ref: File:///configs/ondemand-flow-1/input.yaml
    protocol:
      $ref: File:///configs/ondemand-flow-1/protocolMapping.yaml
    calls:
      $ref: File:///configs/ondemand-flow-1/protocolCalls.yaml
  - summary: intercity-code-based  
    domain: ONDC:TRV12
    id: intercity-code-based
    input:
      $ref: File:///configs/intercity-code-based/input.yaml
    protocol:
      $ref: File:///configs/intercity-code-based/protocolMapping.yaml
    calls:
      $ref: File:///configs/intercity-code-based/protocolCalls.yaml

